<a href="https://colab.research.google.com/github/al0214/PMG_END/blob/main/0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install -U scikit-learn

In [ ]:
import sklearn
import numpy as np

import xgboost
import lightgbm

In [ ]:
array1 = np.array([1,2,3])
print(f'array 1 type:{type(array1)}')
print(f'array 1 array 형태 : {array1.shape} \n')

array2 = np.array([[1,2,3], [2,3,4,]])
print(f'array 2 type:{type(array2)}')
print(f'array 2 array 형태 : {array2.shape} \n')

array3 = np.array([[1,2,3]])
print(f'array 3 type:{type(array3)}')
print(f'array 3 array 형태 : {array3.shape}')

array 1 type:<class 'numpy.ndarray'>
array 1 array 형태 : (3,) 

array 2 type:<class 'numpy.ndarray'>
array 2 array 형태 : (2, 3) 

array 3 type:<class 'numpy.ndarray'>
array 3 array 형태 : (1, 3)


In [ ]:
print('array 1 : {:0}차원, array 2 : {:1}차원, array 3 : {:2}차원,'.format(array1.ndim, array2.ndim, array3.ndim))

array 1 : 1차원, array 2 : 2차원, array 3 :  2차원,


In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
def printtype(a):
  return print(f'{a} \n {a.dtype} {a.shape}')

In [ ]:
zero_array = np.zeros((3,2), dtype='int32')
printtype(zero_array)

one_array = np.ones((3,2))
printtype(one_array)

[[0 0]
 [0 0]
 [0 0]] 
 int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]] 
 float64 (3, 2)


In [ ]:
import pandas as pd

In [ ]:
titanic_df = pd.read_csv('/content/drive/MyDrive/Machine-Learning-Study/data/train.csv')

In [ ]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [ ]:
print(f'titanic 변수 type : {type(titanic_df)}')

titanic 변수 type : <class 'pandas.core.frame.DataFrame'>


In [ ]:
print(f'DataFrame 크기 : {titanic_df.shape}')

DataFrame 크기 : (891, 12)


In [ ]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [ ]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [ ]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [ ]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
