<a href="https://colab.research.google.com/github/al0214/PMG_END/blob/main/0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install -U scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 94.6 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.7.0 which is incompatible.


In [2]:
import sklearn
import numpy as np

import xgboost
import lightgbm

In [8]:
def printtype(a):
  return print(f'{a} \n {a.dtype} {a.shape}')

In [3]:
array1 = np.array([1,2,3])
print(f'array 1 type:{type(array1)}')
print(f'array 1 array 형태 : {array1.shape} \n')

array2 = np.array([[1,2,3], [2,3,4,]])
print(f'array 2 type:{type(array2)}')
print(f'array 2 array 형태 : {array2.shape} \n')

array3 = np.array([[1,2,3]])
print(f'array 3 type:{type(array3)}')
print(f'array 3 array 형태 : {array3.shape}')

array 1 type:<class 'numpy.ndarray'>
array 1 array 형태 : (3,) 

array 2 type:<class 'numpy.ndarray'>
array 2 array 형태 : (2, 3) 

array 3 type:<class 'numpy.ndarray'>
array 3 array 형태 : (1, 3)


In [4]:
print('array 1 : {:0}차원, array 2 : {:1}차원, array 3 : {:2}차원,'.format(array1.ndim, array2.ndim, array3.ndim))

array 1 : 1차원, array 2 : 2차원, array 3 :  2차원,


In [5]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [6]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [9]:
zero_array = np.zeros((3,2), dtype='int32')
printtype(zero_array)

one_array = np.ones((3,2))
printtype(one_array)

[[0 0]
 [0 0]
 [0 0]] 
 int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]] 
 float64 (3, 2)


In [31]:
array1 = np.arange(10)
array1 = array1.reshape(-1,5)
printtype(array1)

[[0 1 2 3 4]
 [5 6 7 8 9]] 
 int64 (2, 5)


In [30]:
array1d = np.arange(4)
array1d = array1d.reshape(-1, 1)

printtype(array1d)

[[0]
 [1]
 [2]
 [3]] 
 int64 (4, 1)


In [34]:
array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2d.shape

(3, 3)

In [45]:
array1d[array1d>5]

array([], dtype=int64)

In [44]:
array2d[[0,1], 2]

array([3, 6])

In [52]:
array1 = [3, 1, 9, 5]
np.argsort(array1)[::-1]

array([2, 3, 0, 1])